name: test

on:
  push:

jobs:
  check:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        rustc: [1.75.0, 1.76.0, 1.77.0, 1.78.0, 1.79.0, 1.80.0, 1.81.0, 1.82.0, 1.83.0, 1.84.0, 1.85.0]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Temporarily modify the rust toolchain version
        run: rustup override set ${{ matrix.rustc }}

      - name: Setup rust formatter
        run: |
          rustup component add rustfmt

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ matrix.rustc }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Format check
        run: cargo fmt --check

      - name: Test
        run: cargo test

      - name: Doc check
        run: cargo doc

      - name: Build check
        run: cargo build


